### ISSUE TITLE
JS Graph & Visualization libraries

### ISSUE THREAD

**Issue by Hephest** [Hephest/coinweb-blockexplorer#12]
Perform a research for proper Javascript library, which we can use in future for 'Stats' page. Add info about this lib's by next template:

* lib name
* link to official site / documentation
* advantages & disadvantages 

P.S. Write each new library **separately**, in different messeges to thi issue. Hope you can find up to 7 lib's, so we can use one of them
P.S.S. Just JS lib's, no frameworks!

**Comment by Volekss** [comment]
- Google Charts

- https://developers.google.com/chart/

- advantages:  quite good lib for this case. It provides lots of features and various cross-platform customization. Charts are rendered using HTML5/SVG and includes VML for supporting older IE version. `<del>(can't imagine who uses them)</del>` . Library provides you with many pre-bilt charts.

- hard to find them.

- check examples here: https://developers.google.com/chart/interactive/docs/gallery

**Comment by Volekss** [comment]
- ChartJS

- http://www.chartjs.org/

- advantages:  quite nice flat design (could not fit our design). It uses HTML5 canvas element for rendering. Support for older browsers like IE7/8 is added through polyfill. REsponsive design.

- disadvantges: could be flat design

**Comment by Volekss** [comment]
- Chartist.js

- http://gionkunz.github.io/chartist-js/

- advantages: uses SVG to render the charts. It can be controlled and customised through CSS3 media queries and Sass. Cool animations. Responsive design.

- disadvantages: Cool animations will work only in modern browsers.

**Comment by Volekss** [comment]
- n3-charts

- http://n3-charts.github.io/line-chart/#/home

- good if you use AngularJs

**Comment by Hephest** [comment]
Good job. We should use one of them.
